---
title: "ASL Records"
editor_options: 
  chunk_output_type: console
---

## ASL Honour Board


```{r, setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(stringsAsFactors = FALSE)

library(tidyverse)
library(reactable)
library(htmltools)
```

```{r league_data}

league_master <- read.csv('../data/master/league_master.csv')
league_data <- readRDS('../data/2022/league_data.RDS')

```


```{r honour_data}

honour_data <- tibble(
  position = seq(1,8),
  '2013' = c('Simon','Mark','Lester','Jordan','Paul','Luke','James','Autobot'),
  '2014' = c('Simon','Lester','Anthony','Jordan','Mark','Luke','James','Paul'),
  '2015' = c('Anthony','Paul','Simon','Lester','Luke','Jordan','James','Mark'),
  '2016' = c('Anthony','Simon','Luke','James','Paul','Lester','Mark','Jordan'),
  '2017' = c('Paul','Jordan','Luke','Lester','Mark','James','Anthony','Simon'),
  '2018' = c('Luke','Simon','Anthony','Jordan','Lester','James','Paul','Mark'),
  '2019' = c('Luke','Paul','Anthony','Jordan','Lester','James','Mark','Simon'),
  '2020' = c('Mark','Simon','Lester','Jordan','Luke','Paul','James','Anthony'),
  '2021' = c('Paul','James','Anthony','Luke','Lester','Jordan','Mark','Simon')
) %>%
  pivot_longer(starts_with('20'), names_to='season',values_to='coach') %>%
  mutate(season = as.numeric(season))

honour_smy <- honour_data %>%
  group_by(coach) %>%
  summarise(
    seasons=n(),
    champ = sum(ifelse(position==1,1,0)),
    gfinal = sum(ifelse(position<=2,1,0)),
    finals = sum(ifelse(position<=4,1,0)),
    spoon= sum(ifelse(position==8,1,0))
  ) %>%
  ungroup() %>%
  filter(coach != 'Autobot') %>%
  mutate(trophy_case = champ + (gfinal + finals - (spoon*2))*0.01) %>%
  arrange(desc(trophy_case), desc(gfinal), desc(finals), spoon) %>%
  mutate(trophy_case = row_number()) %>%
  mutate(pcnt_champ = round(champ/seasons,2)) %>%
  mutate(pcnt_gfinal = round(gfinal/seasons,2)) %>%
  mutate(pcnt_finals = round(finals/seasons,2)) %>%
  mutate(pcnt_spoon = round(spoon/seasons,2)) 
  
overall_ladder <- league_data %>%
  filter(!is.na(team_score)) %>%
  bind_rows(league_master) %>%
  group_by(coach) %>%
  summarise(
    played = n(),
    wins = sum(win),
    draws = sum(draw),
    losses = sum(loss),
    win_pcnt = round(sum(win)/n(),3),
    avg_score= round(sum(team_score)/n()),
    avg_against= round(sum(opponent_score)/n()),
    pcnt = round(sum(team_score)/sum(opponent_score)*100,1),
    .groups='drop'
  ) %>%
  arrange(desc(win_pcnt))


honour_smy <- honour_smy[,c('coach','trophy_case','seasons','champ','gfinal','finals','spoon')] 
```
```{r honour_table, echo=FALSE}

rating_column <- function(maxWidth = 55, class = NULL, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = paste("cell number", class), ...)
}
knockout_column <- function(maxWidth = 80, class = NULL, ...) {
  colDef(
    #cell = format_pct,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      x <- value/max(honour_smy$seasons)
      
      # Lighter color for <1%
      if (x < 0.01) {
        list(color = "#aaa")
      } else {
        list(color = "#111", background = knockout_pct_color(x))
      }
    },
    ...
  )
}
format_pct <- function(value) {
  if (value == 0) "  \u2013 "    # en dash for 0%
  else if (value == 1) "\u2713"  # checkmark for 100%
  else if (value < 0.01) " <1%"
  else if (value > 0.99) ">99%"
  else formatC(paste0(round(value * 100), "%"), width = 4)
}
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
knockout_pct_color <- make_color_pal(c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"), bias = 2)

award_cols <- c('champ','gfinal','finals','spoon')
ladder_cols <- c("played","wins","draws","losses","win_pcnt","avg_score","avg_against","pcnt")



tbl <- reactable(
  honour_smy,
  pagination = FALSE,
  defaultColDef = colDef(class = "cell", headerClass = "header"),
  defaultColGroup = colGroup(headerClass = "header"),
  columnGroups = list(
    colGroup(name = "Achievements", columns = award_cols)
  ),
  columns = list(
    coach = colDef(
      defaultSortOrder = "asc",
      maxWidth = 100,
      headerStyle = list(fontWeight = 700), 
      cell = function(value) {
        div(
          class = "team",
          div(class = "team-name", value)
        )
      }
    ),
    trophy_case = colDef(
      name = "Trophy Case",
      defaultSortOrder = "desc",
      minWidth = 150,
      headerStyle = list(fontWeight = 700), 
      align='left',
      class = "cell border-left",
      cell = function(value, index) {
        
        value <- honour_smy$coach[[index]]
        
        img_data <- honour_data %>%
          arrange(season) %>%
          filter(position == 1 | position == 8) %>%
          filter(coach == value)
        
        img_list <- list()
        
        if(nrow(img_data)>0){
          for(i in 1:nrow(img_data)){
            if(img_data$position[i] == 1){
              img <- img(class = "flag", alt = 'champ', title=img_data$season[[i]], src = sprintf("images/DB_%s.png", img_data$season[[i]]))
              img_list[[i]] <- img
            } else {
              img <- img(class = "flag", alt = 'spoon', src = "images/spoon.png")
              img_list[[i]] <- img
            }
          }
        }
        
        div(
          class = "team",
          img_list
        )
      }
    ),
    seasons = colDef(show=FALSE),
    champ = knockout_column(name = "Dawn Breakers", class="border-left"),
    gfinal = knockout_column(name = "Grand Finals"),
    finals = knockout_column(name = "Finals"),
    spoon = knockout_column(name = "Spoons")
  ),
  # Emphasize borders between groups when sorting by group
  rowClass = JS("
    function(rowInfo, state) {
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'group') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row.group !== nextRow.group) {
          return 'group-last'
        }
      }
    }"
  ),
  showSortIcon = FALSE,
  borderless = TRUE,
  class = "standings-table"
)
div(class = "standings",
  tbl
)
```
```{r}
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```
```{css}
.standings {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
}
.title {
  margin: 18px 0;
  font-size: 16px;
}
.title h2 {
  font-size: 20px;
  font-weight: 600;
}
.standings-table {
  margin-bottom: 20px;
}
/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}
.header {
  border-bottom-color: #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}
/* Highlight headers when sorting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}
.border-left {
  border-left: 2px solid #555;
}
/* Use box-shadow to create row borders that appear behind vertical borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
}
.group-last .cell {
  box-shadow: inset 0 -2px 0 #555;
}
.team {
  display: flex;
  align-items: center;
}
.record {
  margin-left: 5px;
  color: #999;
  font-size: 13px;
}
.team-name {
  font-size: 18px;
  font-weight: 700;
}
.flag {
  margin-right: 8px;
  height: 30px;
}
.group {
  font-size: 19px;
}
.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 16px;
  line-height: 30px;
  white-space: pre;
}
.spi-rating {
  width: 30px;
  height: 30px;
  border: 1px solid rgba(0, 0, 0, 0.03);
  border-radius: 50%;
  color: #000;
  font-size: 13px;
  letter-spacing: -2px;
  align: "center";
}

.small-font {
  font-size: 13px;
}
```
```{css echo=FALSE}
/* rmarkdown html documents */
h1.title {
  display: none;
}
/* pkgdown articles */
.page-header {
  display: none;
}
```




```{r h2h}
# 
# h2h_data <- league_master %>%
#   group_by(coach, opponent_coach) %>%
#   summarise(
#     wins = sum(win),
#     losses = sum(loss),
#     .groups='drop'
#   ) %>%
#   arrange(opponent_coach) %>%
#   mutate(win_loss = paste0(wins," - ",losses)) %>%
#   select(-wins, -losses)
# 
# 
# x <-h2h_data %>%
#   pivot_wider(names_from=opponent_coach,values_from = win_loss) %>%
#   arrange(coach)




```
