---
title: "Fantasy Banter"
---

```{r, setup, echo=FALSE, include=FALSE}
options(stringsAsFactors = FALSE)

library(tidyverse)
library(highcharter)
library(zoo)
library(janitor)
library(shiny)
library(DT)
library(kableExtra)

```

```{r, echo=FALSE,include=FALSE}
source('/Users/paulmcgrath/Github/Addicts-Supercoach-League/functions/supercoach_functions.R')

#player_data <- get_player_data(cid,tkn)
#fixture_data <- get_fixture_data(cid, tkn)

#saveRDS(player_data, '../data/2021/player_data.RDS')
#saveRDS(fixture_data, '../data/2021/fixture_data.RDS')

player_data <- readRDS('../data/2021/player_data.RDS')
fixture_data <- readRDS('../data/2021/fixture_data.RDS')

```

## Score Summary
```{r, boxplots, echo=FALSE}

boxplot_data <- fixture_data %>%
  filter(!is.na(team_score)) %>%
  filter(team_score > 0)
  
box_summary <- boxplot(team_score ~ coach, data = boxplot_data, range=3, plot=FALSE)
box_order <- rev(order(box_summary$stats[3,]))
box_data <- t(box_summary$stats[,box_order])
rownames(box_data) <- box_summary$names[box_order]

highchart() %>%
  hc_chart(type = 'boxplot') %>%
  hc_xAxis(categories = box_summary$names[box_order]) %>%
  hc_add_series(data=box_data)

```

## Power Rankings
```{r, power_rankings, echo=FALSE}

rankings_data <- fixture_data %>%
  filter(!is.na(team_score)) %>%
  filter(team_score > 0) %>%
  select(round, team, coach, team_score) %>% 
  arrange(coach, round) %>%
  group_by(coach) %>%
  mutate(avg3 = round(rollapply(team_score,3,mean,align='right',fill='extend'),1)) %>%
  ungroup() %>%
  select(round, coach, avg3) %>%
  spread(coach, avg3)

#  rank(rankings_data[nrow(rankings_data),c(2:9)]) -
# rank(rankings_data[nrow(rankings_data)-1,c(2:9)])

highchart() %>%
  hc_chart(type = 'spline') %>%
  hc_xAxis(categories=rankings_data$round) %>%
  hc_add_series(name=colnames(rankings_data)[2], data=rankings_data$Anthony) %>%
  hc_add_series(name=colnames(rankings_data)[3], data=rankings_data$James)  %>%
  hc_add_series(name=colnames(rankings_data)[4], data=rankings_data$Jordan)  %>%
  hc_add_series(name=colnames(rankings_data)[5], data=rankings_data$Lester)  %>%
  hc_add_series(name=colnames(rankings_data)[6], data=rankings_data$Luke)  %>%
  hc_add_series(name=colnames(rankings_data)[7], data=rankings_data$Mark)  %>%
  hc_add_series(name=colnames(rankings_data)[8], data=rankings_data$Paul)  %>%
  hc_add_series(name=colnames(rankings_data)[9], data=rankings_data$Simon) 

```

## ASL Team of the Week
```{r, team_of_the_week, echo=FALSE}

totw_data <- player_data %>%
  filter(!is.na(team)) %>%
  filter(type == 'scoring') %>%
  arrange(round, position, desc(points), desc(avg)) %>%
  group_by(round, position) %>%
  mutate(rank = rank(-points, ties.method='first')) %>%
  filter((position == 'DEF' & rank <= 5)|
         (position == 'MID' & rank <= 7)|
         (position == 'RUC' & rank <= 1)|
         (position == 'FWD' & rank <= 5)) %>%
  ungroup()
           
totw_summary <- totw_data %>%
  group_by(coach, position) %>%
  summarise(
    n = n(),
    .groups='drop'
  ) %>%
  spread(coach, n) %>%
  adorn_totals('row')

totw <- totw_data %>%
  filter(round == max(round)) %>%
  mutate(name=paste0(substr(first_name,1,1),'.',last_name)) %>%
  select(position, rank, name, points, coach)

totw <- bind_rows(totw[totw$position!='FWD',], totw[totw$position=='FWD',]) %>%
  select(rank, name, points, coach)

kbl(totw) %>%
  kable_paper("striped", full_width = F) %>%
  pack_rows("Defence", 1, 5) %>%
  pack_rows("Midfield", 6, 12) %>%
  pack_rows("Ruck", 13, 13) %>%
  pack_rows("Forward", 14, 18) 

kbl(totw_summary[c(1,3,4,2,5),c(1, rev(order(totw_summary[5,c(2:9)])+1))])
```

## Wish list
- team of the week
- injury assessment
- fixture strength
- waiver team of the round
- trade tracker
- positional averages
- draft heat map
- simulations/to make finals
- ladder predictor
- ladder journey
- records
- H2H matchups 
- B&F
